# Generated by Django 3.2.23 on 2025-10-17 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalerieMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type_media', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=10, verbose_name='Type de média')),
                ('categorie', models.CharField(choices=[('evenement', 'Événement'), ('action', 'Action de terrain'), ('formation', 'Formation'), ('sensibilisation', 'Sensibilisation'), ('partenariat', 'Partenariat'), ('autre', 'Autre')], default='evenement', max_length=20, verbose_name='Catégorie')),
                ('image', models.ImageField(blank=True, null=True, upload_to='galerie/images/', verbose_name='Image')),
                ('video', models.FileField(blank=True, null=True, upload_to='galerie/videos/', verbose_name='Fichier vidéo')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL vidéo (YouTube, Vimeo, etc.)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_evenement', models.DateField(blank=True, null=True, verbose_name="Date de l'événement")),
                ('lieu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu')),
                ('actif', models.BooleanField(default=True, verbose_name='Visible sur le site')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name': 'Média de galerie',
                'verbose_name_plural': 'Médias de galerie',
                'ordering': ['-ordre', '-date_creation'],
            },
        ),
    ]
