# Generated by Django 3.2.23 on 2025-11-07 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0007_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du donateur')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (€)')),
                ('type_don', models.CharField(choices=[('unique', 'Don unique'), ('mensuel', 'Don mensuel')], default='unique', max_length=10, verbose_name='Type de don')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message (optionnel)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('paypal_complete', models.BooleanField(default=False, verbose_name='Paiement PayPal complété')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-date_creation'],
            },
        ),
    ]
