"""
Django settings for blog_projet project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-!j0onpvp9uhgmw$qlfpw)h7w_0g*_e-sjycd^x3a6r8vbcp=8z')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Allowed hosts - allow Railway domain and custom domains
if 'RAILWAY_ENVIRONMENT' in os.environ:
    ALLOWED_HOSTS = ['*']  # Railway domains
else:
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Notre app
    'blog_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Pour servir les fichiers statiques
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog_projet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog_projet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# Base de données PostgreSQL pour Railway
import os

if 'RAILWAY_ENVIRONMENT' in os.environ or 'DATABASE_URL' in os.environ:
    # Configuration Railway (production)
    database_url = os.environ.get('DATABASE_URL', '')
    
    # Vérifier que l'URL existe et est valide
    if database_url and database_url.strip():
        DATABASES = {
            'default': dj_database_url.parse(database_url)
        }
    else:
        # Fallback en cas de problème
        raise ValueError(f"DATABASE_URL is not configured properly. Value: '{database_url}'")
else:
    # Configuration locale (développement)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration des fichiers médias

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Redirection après connexion
LOGIN_REDIRECT_URL = 'profil'   # après login → page profil
#LOGOUT_REDIRECT_URL = 'home'  # après logout → page d'accueil

# Configuration CSRF pour AJAX
CSRF_COOKIE_HTTPONLY = False  # Permet à JavaScript d'accéder au cookie CSRF
CSRF_USE_SESSIONS = False      # Utiliser les cookies au lieu des sessions

# Configuration des fichiers statiques

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Pour collectstatic en production

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# ============================================
# 🚀 CONFIGURATION JAZZMIN ULTRA-PROFESSIONNELLE
# Interface Admin Premium pour Ndoti Blog
# ============================================

JAZZMIN_SETTINGS = {
    # ===== BRANDING =====
    "site_title": "Ndoti Admin Pro",
    "site_header": "🌱 Espace Administration Ndoti",
    "site_brand": "Ndoti Blog",
    "site_logo": None,  # Vous pouvez ajouter: "images/logo-admin.png"
    "site_logo_classes": "img-circle elevation-3",
    "site_icon": "🌱",
    "welcome_sign": "Bienvenue dans votre espace d'administration professionnel",
    "copyright": "© 2025 Association Ndoti - Tous droits réservés",
    
    # ===== RECHERCHE INTELLIGENTE =====
    "search_model": [
        "blog_app.Article", 
        "blog_app.Commentaire", 
        "blog_app.Contact",
        "auth.User"
    ],
    
    # ===== MENU UTILISATEUR =====
    "user_avatar": None,
    "show_ui_builder": False,
    
    # ===== MENU SUPÉRIEUR (Top Menu) - DÉSACTIVÉ pour interface épurée =====
    "topmenu_links": [],  # Menu supérieur désactivé pour plus de clarté
    
    # ===== MENU UTILISATEUR (Dropdown) =====
    "usermenu_links": [
        {
            "name": "🌍 Voir le site public",
            "url": "/",
            "new_window": True
        },
        {
            "name": "👤 Mon profil",
            "url": "/profil/",
            "new_window": True
        },
        {
            "model": "auth.user"
        }
    ],
    
    # ===== SIDEBAR CONFIGURATION =====
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "blog_app",
        "blog_app.article",
        "blog_app.commentaire",
        "blog_app.galeriemedia",
        "blog_app.contact",
        "blog_app.profile",
        "auth",
    ],
    
    # ===== ICÔNES MAGNIFIQUES =====
    "icons": {
        # Authentification
        "auth": "fas fa-shield-alt",
        "auth.user": "fas fa-user-shield",
        "auth.Group": "fas fa-users-cog",
        
        # Application Ndoti Blog
        "blog_app": "fas fa-blog",
        "blog_app.Article": "fas fa-newspaper",
        "blog_app.Commentaire": "fas fa-comments",
        "blog_app.Profile": "fas fa-user-circle",
        "blog_app.Contact": "fas fa-envelope-open-text",
        "blog_app.GalerieMedia": "fas fa-photo-video",
    },
    
    # ===== ICÔNES PAR DÉFAUT =====
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-file",
    
    # ===== INTERFACE & COMPORTEMENT =====
    "related_modal_active": True,
    "custom_css": "admin/css/ndoti-admin-pro.css",
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    
    # ===== FORMAT DES FORMULAIRES =====
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
        "blog_app.article": "horizontal_tabs",
    },
    
    # ===== FILTRES & OPTIONS =====
    "language_chooser": False,
}


# ============================================
# 🎨 PERSONNALISATION UI ULTRA-PREMIUM
# Thème visuel professionnel Ndoti
# ============================================

JAZZMIN_UI_TWEAKS = {
    # ===== TYPOGRAPHIE =====
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    
    # ===== COULEURS PRINCIPALES =====
    "brand_colour": "#91CD8C",           # Vert Ndoti - Logo & Branding
    "accent": "#fbbf24",                  # Jaune Ndoti - Accents & CTA
    "navbar": "#91CD8C",                  # Barre de navigation principale
    "no_navbar_border": True,             # Navigation sans bordure (moderne)
    
    # ===== SIDEBAR PREMIUM =====
    "sidebar": "sidebar-dark-success",    # Sidebar vert foncé élégant
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,       # Style plat moderne
    "sidebar_fixed": True,                # Sidebar fixe au scroll
    
    # ===== LAYOUT & STRUCTURE =====
    "navbar_fixed": True,                 # Navbar fixe au scroll
    "layout_boxed": False,                # Full width (moderne)
    "footer_fixed": False,
    
    # ===== THÈME GLOBAL =====
    "theme": "flatly",                    # Thème Bootstrap moderne
    "dark_mode_theme": None,              # Mode clair uniquement
    
    # ===== BOUTONS & ACTIONS =====
    "button_classes": {
        "primary": "btn-success",         # Boutons verts principaux
        "secondary": "btn-outline-success",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    
    # ===== ACTIONS =====
    "actions_sticky_top": True,           # Actions toujours visibles
}

# ============================================
# 🌐 CONFIGURATION POUR RENDER DÉPLOIEMENT
# ============================================

# Configuration des fichiers statiques pour production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Configuration sécurité pour production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 86400
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Configuration des médias pour production (utilisation de services cloud recommandée)
if not DEBUG:
    # Pour la production, il est recommandé d'utiliser un service de stockage cloud
    # comme AWS S3, Cloudinary, etc. pour les fichiers media
    pass

# Configuration du timezone
TIME_ZONE = 'Europe/Paris'
LANGUAGE_CODE = 'fr-fr'